services:
   db:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=vishal
      - POSTGRES_PASSWORD=vishal@43
      - POSTGRES_DB=apimonitor
    volumes:
      - ./pgdata:/var/lib/postgresql/data
   redis:
     image: redis:7-alpine
     container_name: redis
     ports:
      - "6379:6379"
volumes:  
  pgdata:
